ConnectWebApp/st10102257_APPR6312_DIS3_Gr2_Part1/Pages/workspace/AllocateDonation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using st10102257_APPR6312_DIS3_Gr2_Part1.Data;
using st10102257_APPR6312_DIS3_Gr2_Part1.Model;

namespace st10102257_APPR6312_DIS3_Gr2_Part1.Pages.workspace
{
    public class AllocateDonationModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public IEnumerable<GoodsDonations> Donations { get; set; }
        public IEnumerable<Categories> Categories { get; set; }
        public List<DonationWithCategoryName> DonationsWithCategories { get; set; }
        public GoodsDonations Donation { get; set; }
        public Disasters Disaster { get; set; }
        public int DonatonId { get; set; }
        public int disasterId { get; set; }
        public AllocateDonationModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public void OnGet(int disasterId)
        {
            this.disasterId = disasterId;

            // Get categories
            Categories = _db.Categories.ToList(); 

           
            if (disasterId != null)
            {
                // Retrieve the donation with donation id
                Disaster = _db.Disasters.FirstOrDefault(d => d.ID == disasterId);
            }
            else
            {
                // Initialize Donation to an empty or default object
                Donation = new GoodsDonations(); // Replace with the appropriate constructor
            }


        }

        public IActionResult OnPost()
        {
            int category = Convert.ToInt32(Request.Form["category"]);
            decimal amount = Convert.ToDecimal(Request.Form["amount_to_send"]);
            int disaster = Convert.ToInt32(Request.Form["disasterId"]);

            var disasterObj = _db.Disasters.Find(disaster);

            var allocationObj = new Allocation();

            var canBeAllocateTo = allocationObj.CanBeAllocatedTo(disasterObj);

            if (!canBeAllocateTo)
            {
                TempData["StatusMessage"] = "Cannot allocate to a disaster that is not active.";
                return RedirectToPage("Dashboard");
            }

            // Prepare objects to update or add to the database
            var updateCategory = _db.Categories.FirstOrDefault(d => d.ID == category);
            var allocation = new Allocation
            {
                DisasterId = disaster,
                Amount = amount,
                CategoryId = category,
            };

            if(updateCategory != null)
            {
                // Perform database functions
                _db.Add(allocation);
                decimal amountRemaining = updateCategory.Total - amount;     // subtract the amount
                updateCategory.Total = amountRemaining;     // Update amount in inventory
                _db.SaveChanges();
                TempData["StatusMessage"] = "Allocation was successful.";
            }
            else
            {
                TempData["StatusMessage"] = "Failed to allocate.";
            }


            return RedirectToPage("Dashboard");
        }
    }
}

ConnectWebApp/st10102257_APPR6312_DIS3_Gr2_Part1/Pages/workspace/Dashboard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using st10102257_APPR6312_DIS3_Gr2_Part1.Data;
using st10102257_APPR6312_DIS3_Gr2_Part1.Model;
using System.Globalization;

namespace st10102257_APPR6312_DIS3_Gr2_Part1.Pages.workspace
{
    public class DashboardModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public IEnumerable<Categories> Categories { get; set; }
        public IEnumerable<GoodsDonations> Donations { get; set; }
        public IEnumerable<Disasters> Disasters { get; set; }
        public IEnumerable<DonationsCombined> AllDonations { get; set; }
        public GoodsDonations Donation { get; set; }
        public List<string> DonationCategories { get; set; }
        public Dictionary<string, decimal> CategoryTotals { get; set; }

        public DashboardModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public void OnGet()
        {
            var goodsDonations = _db.GoodsDonations
                .Include(g => g.Category)
                .Select(g => new DonationsCombined
                {
                    Donor = g.Donor,
                    Date = g.Date,
                    CategoryName = g.Category.Name,
                    Amount = g.Amount,
                    Description = g.Description,
                    isAllocated = g.isAllocated
                }).ToList();
            var monetaryDonations = _db.MonetaryDonations
                .Include(d => d.Category)
                .Select(g => new DonationsCombined
                {
                    Donor = g.Donor,
                    Date = g.Date,
                    CategoryName = g.Category.Name,
                    Amount = g.Amount,
                    Description = g.Description,
                    isAllocated = g.isAllocated
                }).ToList();

            AllDonations = goodsDonations.Union(monetaryDonations).ToList();





            Categories = _db.Categories.ToList();
            // Donations = _db.GoodsDonations
            //    .Include(a => a.Category);
            Disasters = _db.Disasters;

            DonationCategories = Categories.Select(d => d.Name).ToList();

            CategoryTotals = new Dictionary<string, decimal>();

            foreach (var category in DonationCategories)
            {
                decimal totalAmount = AllDonations
                    .Where(d => d.CategoryName == category && !d.isAllocated)
                    .Sum(d => d.Amount);
                CategoryTotals.Add(category, totalAmount);
            }

        }
        public async Task<IActionResult> OnPost(GoodsDonations Donation)
        {
            if (Donation.Date == default(DateTime))
            {
                ModelState.AddModelError("Donation.date", "Date is required.");
                return Page();
            }

            await _db.GoodsDonations.AddAsync(Donation);
            await _db.SaveChangesAsync();
            return RedirectToPage("Dashboard");
        }

        public async Task<IActionResult> OnPostChangeStatus()
        {
            int id = Convert.ToInt32(Request.Form["disaster_id"]);
            bool status = Convert.ToBoolean(Request.Form["status"]);


            // Retrieve the existing disaster from the database
            var disaster = await _db.Disasters.FindAsync(id);

            if (disaster != null)
            {
                // Update the property value
                disaster.isActive = status;

                // Save the changes to the database
                await _db.SaveChangesAsync();

                TempData["StatusMessage"] = "Status was changed successfully.";
            }
            else
            {
                TempData["ErrorMessage"] = "Disaster not found.";
            }

            return RedirectToPage("Dashboard");
        }

    }
}

ConnectWebApp/st10102257_APPR6312_DIS3_Gr2_Part1/Pages/workspace/Disaster.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using st10102257_APPR6312_DIS3_Gr2_Part1.Data;
using st10102257_APPR6312_DIS3_Gr2_Part1.Model;

namespace st10102257_APPR6312_DIS3_Gr2_Part1.Pages.workspace
{
    public class DisasterModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public Disasters Disaster { get; set; }

        public DisasterModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public void OnGet()
        {
            
        }
        public async Task<IActionResult> OnPost(Disasters Disaster)
        {
            await _db.Disasters.AddAsync(Disaster);
            await _db.SaveChangesAsync();
            return RedirectToPage("Dashboard");
        }
    }
}

ConnectWebApp/st10102257_APPR6312_DIS3_Gr2_Part1/Pages/workspace/Donation.cshtml.cs
using Azure.Core.Pipeline;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using st10102257_APPR6312_DIS3_Gr2_Part1.Data;
using st10102257_APPR6312_DIS3_Gr2_Part1.Model;

namespace st10102257_APPR6312_DIS3_Gr2_Part1.Pages.workspace
{
    public class DonationModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public string result = null;
        public IEnumerable<Categories> Categories { get; set; }
        public GoodsDonations Donation { get; set; }
        public MonetaryDonations MonetaryDonation { get; set; }
        public DonationModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public void OnGet()
        {
            Categories = _db.Categories;
        }
        public async Task<IActionResult> OnPostRecordDonation() 
        {
            string donor = Request.Form["donor"];
            int categoryId = Convert.ToInt32(Request.Form["category"]);
            DateTime date = Convert.ToDateTime(Request.Form["date"]);
            decimal amount = Convert.ToDecimal(Request.Form["amount"]);
            string description = Request.Form["description"];

            var categoryName = _db.Categories
                .Where(c => c.ID == categoryId)
                .Select(c => c.Name)
                .FirstOrDefault();
            if (categoryName.ToLower() == "monetary")
            {
                var category = _db.Categories.FirstOrDefault(d => d.ID == categoryId); // get the category
                var newAmount = category.Total + amount;
                var monetaryDonation = new MonetaryDonations
                {
                    Donor = donor,
                    Date = date,
                    CategoryId = categoryId,
                    Amount = amount,
                    Description = description,
                };


                category.Total = newAmount; // Update the amount
                await _db.AddAsync(monetaryDonation);
                await _db.SaveChangesAsync();
            }
            else
            {
                var category = _db.Categories.FirstOrDefault(d => d.ID == categoryId); // get the category
                var newAmount = category.Total + amount;
                var goodsDonation = new GoodsDonations
                {
                    Donor = donor,
                    Date = date,
                    CategoryId = categoryId,
                    Amount = amount,
                    Description = description,
                };

                category.Total = newAmount; // Update the amount
                await _db.GoodsDonations.AddAsync(goodsDonation);
                await _db.SaveChangesAsync();
            }

            return RedirectToPage("Dashboard");
        }

        public async Task<IActionResult> OnPostCreateCategory()
        {
            // Get the value of "CategoryName" from the form
            string categoryName = Request.Form["CategoryName"];

            // Create a new Category object and set its Name property
            var category = new Categories
            {
                Name = categoryName
            };

            // Add the category to the database
            await _db.Categories.AddAsync(category);
            await _db.SaveChangesAsync();

            return RedirectToPage("Donation");

        }

    }
}

ConnectWebApp/st10102257_APPR6312_DIS3_Gr2_Part1/Pages/workspace/PurchaseGoods.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using st10102257_APPR6312_DIS3_Gr2_Part1.Data;
using st10102257_APPR6312_DIS3_Gr2_Part1.Model;

namespace st10102257_APPR6312_DIS3_Gr2_Part1.Pages.workspace
{
    public class PurchaseGoodsModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public IEnumerable<Categories> Categories { get; set; }

        public PurchaseGoodsModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public void OnGet()
        {
            Categories = _db.Categories;
        }

        public IActionResult OnPost()
        {
            int category = Convert.ToInt32(Request.Form["category"]);
            string description = Request.Form["description"];
            decimal amountUsed = Convert.ToDecimal(Request.Form["amount_used"]);
            decimal items = Convert.ToDecimal(Request.Form["items_count"]);
            DateTime date = Convert.ToDateTime(Request.Form["date"]);

            var monetaryCategory = _db.Categories.FirstOrDefault(d => d.Name.ToLower() == "monetary");
            var goodsCategory = _db.Categories.FirstOrDefault(d => d.ID == category);

            if(monetaryCategory != null)
            {
                var newAmount = monetaryCategory.Total - amountUsed;
                var newItemCount = goodsCategory.Total + items;
                var goodsDonations = new GoodsDonations
                {
                    Donor = "PURCHASED",
                    CategoryId = category,
                    Date = date,
                    Description = description,
                    Amount = items,
                };

                goodsCategory.Total = newItemCount;
                _db.Add(goodsDonations);        // Save to database
                _db.SaveChanges();

                int donationId = goodsDonations.ID;

                var goodsPurchased = new GoodsPurchased
                {
                    AmountUsed = amountUsed,
                    GoodsDonationsId = donationId
                };

                monetaryCategory.Total = newAmount;      // Update the amount in inventory
                _db.Add(goodsPurchased);
                _db.SaveChanges();

                TempData["StatusMessage"] = "A new purchased was successfully added.";
            }
            else
            {
                TempData["StatusMessage"] = "Could not add a new purchase, Try again.";
            }
           
            return RedirectToPage("Dashboard");
        }
    }
}

ConnectWebApp/st10102257_APPR6312_DIS3_Gr2_Part1/Pages/workspace/AllocateDonation.cshtml
@page "/AllocateDonation/{disasterId}"
@model st10102257_APPR6312_DIS3_Gr2_Part1.Pages.workspace.AllocateDonationModel // Change the namespace
@{
}
<div class="row d-flex justify-content-center">
    
    <form method="post" id="allocate_form" class="col-8">
        <div class="row">
            <input type="hidden" name="disasterId" class="form-control" id="disasterId" value="@Model.disasterId" aria-describedby="inputGroupPrepend">
            <input type="hidden" name="donationId" class="form-control" id="donationId" aria-describedby="inputGroupPrepend">
            <div class="row">
                <div class="col-md-6">
                    <p><strong>Disaster</strong>:   @Model.Disaster?.Name</p>
                </div>
                <div class="col-md-6">
                    <p><strong>Location</strong>:   @Model.Disaster?.Location</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <p><strong>Started</strong>: @Model.Disaster?.startDate.ToString("dd-MMM-yyyy")</p>
                </div>
                <div class="col-md-6">
                    <p><strong>Ended</strong>: @Model.Disaster?.endDate.ToString("dd-MMM-yyyy")</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p><strong>Description</strong>: @Model.Disaster?.Description</p>
                </div>
            </div>
            <div class="col-6">
                <label class="form-label">Select from categories</label>
                <select class="form-select" name="category" id="categorySelect" required>
                    <option selected disabled value="">Choose...</option>
                    @foreach (var obj in Model.Categories)
                    {
                        <option value="@obj.ID" data-available="@obj.Total">@obj.Name (Available: @(obj.Name.ToLower() == "monetary" ? "R " + obj.Total : (int)obj.Total + " items"))</option>
                    }
                </select>
            </div>
            <div class="col-6">
                <label class="form-label">Amount of money/items to send</label>
                <input type="text" name="amount_to_send"  class="form-control" id="amountInput">
            </div>
        </div>
        <div class="row pt-3">
            <button type="submit" class="btn btn-sm btn-custom-orange" id="allocateBtn" disabled>Allocate</button>
        </div>
    </form>
</div>


<script>

    // Get references to elements
    const categorySelect = document.getElementById("categorySelect");
    const amountInput = document.getElementById("amountInput");
    const submitButton = document.getElementById("allocateBtn");

    // Attach an event listener to the amount input
    amountInput.addEventListener("input", function () {
        const selectedOption = categorySelect.options[categorySelect.selectedIndex];
        const availableAmount = parseFloat(selectedOption.getAttribute("data-available"));
        const enteredAmount = parseFloat(amountInput.value);

        // Enable or disable the submit button based on the comparison
        submitButton.disabled = enteredAmount > availableAmount;
    });
</script>

ConnectWebApp/st10102257_APPR6312_DIS3_Gr2_Part1/Pages/workspace/Disaster.cshtml
@page
@model st10102257_APPR6312_DIS3_Gr2_Part1.Pages.workspace.DisasterModel
@{
    ViewData["Title"] = "Disaster";
}


<div class="row">
    <div class="row text-center">
        <div class="d-flex justify-content-start">
            <a href="javascript:history.back()" class="link justify-content-start" style=" text-decoration: none !important"><i class="ri-arrow-left-s-line"></i>&nbsp;Back</a>
        </div>
        <h1 class="display-4">Disaster</h1>
        <p class="lead">
            Record a new disaster
        </p>
    </div>
</div>


<div class="row dlex justify-content-center">
    <div class="col-sm-12 col-md-8 col-lg-8">
        <div class="row ">
            <form method="post" class="row g-3">
                <div class="col-6">
                    <label class="form-label">Disaster</label>
                    <input type="text" asp-for="Disaster.Name" class="form-control" id="donorNameField">
                </div>
                <div class="col-6">
                    <label for="" class="form-label">Location</label>
                    <input type="text" asp-for="Disaster.Location" class="form-control" id="" required>
                </div>
                <div class="col-6">
                    <label for="" class="form-label">Started</label>
                    <div class="input-group ">
                        <span class="input-group-text" id=""></span>
                        <input type="date" asp-for="Disaster.startDate" class="form-control" id="" aria-describedby="inputGroupPrepend" required>
                    </div>
                </div>
                <div class="col-6">
                    <label for="" class="form-label">Ended</label>
                    <div class="input-group ">
                        <span class="input-group-text" id=""></span>
                        <input type="date" asp-for="Disaster.endDate" class="form-control" id="" aria-describedby="inputGroupPrepend" required>
                    </div>
                </div>
                <div class="col-md-12">
                    <label for="" class="form-label">Description</label>
                    <div class="input-group ">
                        <textarea asp-for="Disaster.Description" class="form-control" id="" rows="3" aria-describedby="inputGroupPrepend" required></textarea>
                    </div>
                </div>
                <div class="col-12">
                    <button class="btn btn-custom-dark" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>

</div>

ConnectWebApp/st10102257_APPR6312_DIS3_Gr2_Part1/Pages/workspace/Donation.cshtml
@page
@model st10102257_APPR6312_DIS3_Gr2_Part1.Pages.workspace.DonationModel
@{
    ViewData["Title"] = "Donation";
}

<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="resultLiveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
                Hello, world! This is a toast message.
            </div>
            <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

<div class="row">
    <div class="row text-center">
        <div class="d-flex justify-content-start">
            <a href="javascript:history.back()" class="link justify-content-start" style=" text-decoration: none !important"><i class="ri-arrow-left-s-line"></i>&nbsp;Back</a>
        </div>
        <h1 class="display-4">DONATION</h1>
        <p class="lead">
            On behalf of the person who will be blessed with what you are 
            about to donate, thank you <i class="ri-lg ri-shake-hands-line"></i>
        </p>
    </div>
</div>


<div class="row dlex justify-content-center">
    <div class="col-sm-12 col-md-8 col-lg-8">
        <div class="row p-4">
            <form method="post" asp-page-handler="RecordDonation" class="row g-3">
                  <div class="col-6">
                    <label class="form-label">Donor</label>
                    <input type="text" name="donor"  class="form-control" id="donorNameField">
                    <div class="lead" style="font-size:12px;">
                        <input class="form-check-input" type="checkbox" onclick="isChecked();" value="" id="flexCheckDefault">
                        <label class="form-check-label" for="flexCheckDefault">
                            Anonymous
                        </label>
                    </div>
                  </div>
                  <div class="col-6">
                        <label for="" class="form-label">Date</label>
                        <div class="input-group ">
                              <span class="input-group-text" id=""></span>
                              <input type="date" name="date" class="form-control" id="" aria-describedby="inputGroupPrepend" required>
                        </div>
                  </div>
                <div class="col-6">
                    <label for="validationCustom03" class="form-label">Category</label>
                    <select class="form-select" name="category" required onchange="showModal(this)">
                        <option selected disabled value="">Choose...</option>
                        @foreach(var obj in Model.Categories){
                            <option value="@obj.ID">@obj.Name</option>
                        }
                        <option value="New">New</option>
                    </select>
                </div>
                <div class="col-md-6">
                        <label for="validationCustom04" class="form-label">Amount</label>
                    <div class="input-group ">
                            <span class="input-group-text" id="">#</span>
                            <input type="text"name="amount" class="form-control" id="" aria-describedby="inputGroupPrepend" required>
                    </div>
                </div>
                <div class="col-12">
                    <label for="" class="form-label">Description</label>
                    <textarea rows="3" name="description" class="form-control" id=""></textarea>
                </div>
                <div class="col-12">
                    <button class="btn btn-sm btn-custom-orange" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal" tabindex="-1" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Category</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <!-- Modal Form -->
            <form method="post" asp-page-handler="CreateCategory">
                <div class="modal-body">
                    <p>Enter a new category</p>
                    <div class="col-md-6">
                        <label for="category" class="form-label">Category</label>
                        <div class="input-group">
                            <input type="text" name="CategoryName" class="form-control" id="category" aria-describedby="inputGroupPrepend">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-sm btn-custom-orange" id="saveCategory">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script type = "text/javascript" >

    function showModal(selectElement) {
        if (selectElement.value === 'New') {
            // Use Bootstrap modal method to show your modal
            $('#myModal').modal('show');
        }
    }

    function validateCategory() {
        var categoryInput = document.getElementById("category");
        var reCategoryInput = document.getElementById("re-category");
        var saveButton = document.getElementById("saveCategory");

        // Check if the values of both inputs are the same
        if (categoryInput.value === reCategoryInput.value) {
            // Enable the "Save" button
            saveButton.disabled = false;
        } else {
            // Disable the "Save" button
            saveButton.disabled = true;
        }
    }

    // Add an event listener to trigger the validation on input change
    // document.getElementById("category").addEventListener("input", validateCategory);
    // document.getElementById("re-category").addEventListener("input", validateCategory);


    function isChecked() {
        var donorField = document.getElementById('donorNameField')
        if (document.getElementById('flexCheckDefault').checked) {
            donorField.setAttribute('disabled', '');
            donorField.value = '';
        } else {
                document.getElementById('donorNameField').removeAttribute('disabled');
        }
    }

    const toastTrigger = document.getElementById('saveCategory')
    const toastLiveExample = document.getElementById('resultLiveToast')

    if (toastTrigger) {
      const toastBootstrap = bootstrap.Toast.getOrCreateInstance(toastLiveExample)
      toastTrigger.addEventListener('click', () => {
        toastBootstrap.show()
      })
    }
</script>

ConnectWebApp/st10102257_APPR6312_DIS3_Gr2_Part1/Pages/workspace/PurchaseGoods.cshtml
@page
@model st10102257_APPR6312_DIS3_Gr2_Part1.Pages.workspace.PurchaseGoodsModel
@{
}

<div class="row">
    <div class="row text-center">
        <div class="d-flex justify-content-start">
            <a href="javascript:history.back()" class="link justify-content-start" style=" text-decoration: none !important"><i class="ri-arrow-left-s-line"></i>&nbsp;Back</a>
        </div>
        <h1 class="display-4">Record a New Purchase</h1>
    </div>
</div>


<div class="row dlex justify-content-center">
    <div class="col-sm-12 col-md-8 col-lg-8">
        <div class="row p-4">
            <form method="post" class="row g-3">
                <div class="col-md-6">
                    <label for="validationCustom04" class="form-label">Available Amount</label>
                    <div class="input-group ">
                        <span class="input-group-text" id="">R</span>
                        <input type="text" class="form-control" id="availableAmount" data-data-available="@(Model.Categories.Where(d => d.Name.ToLower() == "monetary").Sum(d => d.Total))" id="" value="@(Model.Categories.Where(d => d.Name.ToLower() == "monetary").Sum(d=> d.Total))" aria-describedby="inputGroupPrepend" readonly>
                    </div>
                </div>
                <div class="col-6">
                    <label for="validationCustom03" class="form-label">Category</label>
                    <select class="form-select" name="category" id="categorySelect" required>
                        <option selected disabled value="">Choose...</option> 
                        @foreach (var obj in Model.Categories)
                        {
                            @if(obj.Name.ToLower() != "monetary"){
                                <option value="@obj.ID">@obj.Name</option>
                            }
                        } 
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="validationCustom04" class="form-label">Number of items to purchase</label>
                    <div class="input-group ">
                        <span class="input-group-text" id="">#</span>
                        <input type="text" name="items_count" class="form-control" id="itemsCountInput" aria-describedby="inputGroupPrepend" required>
                    </div>
                </div>
                  <div class="col-6">
                        <label for="" class="form-label">Date</label>
                        <div class="input-group ">
                              <span class="input-group-text" id=""></span>
                              <input type="date" name="date" class="form-control" id="" aria-describedby="inputGroupPrepend" required>
                        </div>
                  </div>
                <div class="col-md-6">
                    <label for="validationCustom04" class="form-label">Amount to use</label>
                    <div class="input-group ">
                        <span class="input-group-text" id="">R</span>
                        <input type="text" name="amount_used" class="form-control" id="amountInput" aria-describedby="inputGroupPrepend" required>
                    </div>
                </div>
                <div class="col-12">
                    <label for="" class="form-label">Description</label>
                    <textarea rows="3" name="description" class="form-control" id=""></textarea>
                </div>
                <div class="col-12">
                    <button class="btn btn-sm btn-custom-orange" id="purchaseBtn" type="submit" disabled>Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>



<script>
    const availableAmountInput = document.getElementById("availableAmount");
    const amountInput = document.getElementById("amountInput");
    const itemsCountInput = document.getElementById("itemsCountInput");
    const submitButton = document.getElementById("purchaseBtn");

    // Attach event listeners to the amount input and items count input
    amountInput.addEventListener("input", toggleSubmitButtonState);
    itemsCountInput.addEventListener("input", toggleSubmitButtonState);

    function toggleSubmitButtonState() {
        const availableAmount = parseFloat(availableAmountInput.getAttribute("data-data-available"));
        const enteredAmount = parseFloat(amountInput.value);
        const enteredItemCount = parseInt(itemsCountInput.value);

        // Check if both inputs contain numeric values
        const isNumeric = !isNaN(enteredAmount) && !isNaN(enteredItemCount);

        // Enable or disable the submit button based on the comparisons
        submitButton.disabled = !isNumeric || enteredAmount > availableAmount;
    }
</script>